In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(20250501)

---

# Dimensions Set-up

### Period

In [3]:
periods = pd.date_range("2024-01-01", periods=24, freq="MS").strftime("%Y-%m")

### Plant

In [4]:
n_plant = 6
base_cc_count = 10

# PLANTS SIZE
raw_scale = np.random.lognormal(mean=0.0, sigma=0.25, size=n_plant)
scale = raw_scale / raw_scale.mean()   # normalize around 1.0

# PLANTS BIASES
# automation: random factor representing plant automation level (-1 to 1)
# dm_bias: positive bias for high-automation plants (more efficient materials usage)
# dl_bias: negative bias for high-automation plants (less labor needed)
automation = np.random.uniform(-1, 1, n_plant)
dm_bias = np.clip(0.03 * automation, -0.05, 0.05)
dl_bias = np.clip(-0.03 * automation, -0.05, 0.05)

# PRODUCTION vs SUPPORTING CC RATIO
# Higher automation = more supporting CCs needed (less production)
# Larger plants = more supporting CCs needed (less production)
prod_cc_ratio = np.clip(0.75 - 0.15 * automation - 0.10 * (scale - 1), 0.60, 0.85)

# RM/PM RATIO based on plant scale and automation
# Larger/more automated plants have better material control → higher RM ratio
base_rm_ratio = 0.77
rm_ratio = np.clip(
    base_rm_ratio + 0.05 * automation + 0.03 * (scale - 1),
    0.65, 0.80
)

# OH-specific split: high automation → more fixed costs (depreciation, maintenance)
oh_fixed_ratio = 0.35 + 0.15 * automation  # 20–50% fixed depending on automation
oh_var_ratio = 1 - oh_fixed_ratio

plants = {
    f"PLANT {i+1:d}": {
        "SCALE": round(scale[i], 3),
        "AUTOMATION_INDEX": round(automation[i], 3),
        "DM_BIAS": round(dm_bias[i], 3),
        "DL_BIAS": round(dl_bias[i], 3),
        "CC_COUNT": max(3, int(np.random.poisson(base_cc_count*round(scale[i], 3)))),
        "PROD_CC_RATIO": round(prod_cc_ratio[i], 3),
        "PROD_VOLATILITY": round(np.random.uniform(0.05, 0.2), 3),
        "RM_RATIO": round(rm_ratio[i], 3),
        "PM_RATIO": round(1 - rm_ratio[i], 3),
        "OH_FIXED_RATIO": round(oh_fixed_ratio[i], 3),
        "OH_VAR_RATIO": round(oh_var_ratio[i], 3),
    }
    for i in range(n_plant)
}

plant_df = pd.DataFrame.from_dict(plants, orient="index")
plant_df.index.name = "PLANT"
plant_df

,SCALE,AUTOMATION_INDEX,DM_BIAS,DL_BIAS,CC_COUNT,PROD_CC_RATIO,PROD_VOLATILITY,RM_RATIO,PM_RATIO,OH_FIXED_RATIO,OH_VAR_RATIO
PLANT,,,,,,,,,,,
PLANT 1,0.622,-0.584,-0.018,0.018,4,0.850,0.077,0.729,0.271,0.262,0.738
PLANT 2,1.158,-0.782,-0.023,0.023,6,0.850,0.059,0.736,0.264,0.233,0.767
PLANT 3,0.984,-0.173,-0.005,0.005,12,0.778,0.130,0.761,0.239,0.324,0.676
PLANT 4,1.293,0.370,0.011,-0.011,11,0.665,0.090,0.797,0.203,0.406,0.594
PLANT 5,0.913,-0.963,-0.029,0.029,6,0.850,0.144,0.719,0.281,0.206,0.794
PLANT 6,1.029,-0.894,-0.027,0.027,8,0.850,0.125,0.726,0.274,0.216,0.784

### Cost Centers

In [5]:
cc_map = {}
for i, plant in enumerate(plants.keys()):
    n_cc = plants[plant]['CC_COUNT']
    n_prod = max(1, int(n_cc * plants[plant]['PROD_CC_RATIO']))
    n_support = n_cc - n_prod
    
    prod_ccs = [f"CC{i+1:03d}P{j:02d}" for j in range(1, n_prod + 1)]
    support_ccs = [f"CC{i+1:03d}S{j:02d}" for j in range(1, n_support + 1)]
    cc_map[plant] = prod_ccs + support_ccs

cc_df = (
    pd.DataFrame(
        [
            (plant, cc, "Production" if "P" in cc else "Supporting")
            for plant, ccs in cc_map.items()
            for cc in ccs
        ],
        columns=["PLANT", "COST_CENTER", "CAT_CC"]
    )
)
cc_df

      PLANT COST_CENTER      CAT_CC
0   PLANT 1    CC001P01  Production
1   PLANT 1    CC001P02  Production
2   PLANT 1    CC001P03  Production
3   PLANT 1    CC001S01  Supporting
4   PLANT 2    CC002P01  Production
5   PLANT 2    CC002P02  Production
6   PLANT 2    CC002P03  Production
7   PLANT 2    CC002P04  Production
8   PLANT 2    CC002P05  Production
9   PLANT 2    CC002S01  Supporting
10  PLANT 3    CC003P01  Production
11  PLANT 3    CC003P02  Production
12  PLANT 3    CC003P03  Production
13  PLANT 3    CC003P04  Production
14  PLANT 3    CC003P05  Production
15  PLANT 3    CC003P06  Production
16  PLANT 3    CC003P07  Production
17  PLANT 3    CC003P08  Production
18  PLANT 3    CC003P09  Production
19  PLANT 3    CC003S01  Supporting
20  PLANT 3    CC003S02  Supporting
21  PLANT 3    CC003S03  Supporting
22  PLANT 4    CC004P01  Production
23  PLANT 4    CC004P02  Production
24  PLANT 4    CC004P03  Production
25  PLANT 4    CC004P04  Production
26  PLANT 4    CC004P05  Production
27  PLANT 4    CC004P06  Production
28  PLANT 4    CC004P07  Production
29  PLANT 4    CC004S01  Supporting
30  PLANT 4    CC004S02  Supporting
31  PLANT 4    CC004S03  Supporting
32  PLANT 4    CC004S04  Supporting
33  PLANT 5    CC005P01  Production
34  PLANT 5    CC005P02  Production
35  PLANT 5    CC005P03  Production
36  PLANT 5    CC005P04  Production
37  PLANT 5    CC005P05  Production
38  PLANT 5    CC005S01  Supporting
39  PLANT 6    CC006P01  Production
40  PLANT 6    CC006P02  Production
41  PLANT 6    CC006P03  Production
42  PLANT 6    CC006P04  Production
43  PLANT 6    CC006P05  Production
44  PLANT 6    CC006P06  Production
45  PLANT 6    CC006S01  Supporting
46  PLANT 6    CC006S02  Supporting

### COA / Cost Elements

In [6]:
cost_elements = pd.DataFrame(
    [
        ("DM", "RM"),
        ("DM", "PM"),
        ("DL", "DL"),
        ("OH", "OH_FIX"),
        ("OH", "OH_VAR"),
    ],
    columns=["CAT_GL", "COST_ELEMENT"]
)
cost_elements

  CAT_GL COST_ELEMENT
0     DM           RM
1     DM           PM
2     DL           DL
3     OH       OH_FIX
4     OH       OH_VAR

In [7]:
elasticity_range = {
    "RM": (0.85, 0.95),
    "PM": (0.85, 0.95),
    "DL": (0.60, 0.80),
    "OH_VAR": (0.90, 1.05),
    "OH_FIX": (0.00, 0.00),
}

elasticity_table = (
    pd.MultiIndex.from_product(
        [plants.keys(), elasticity_range.keys()],
        names=["PLANT", "COST_ELEMENT"]
    )
    .to_frame(index=False)
)

elasticity_table["ELASTICITY"] = elasticity_table["COST_ELEMENT"].apply(
    lambda x: np.random.uniform(*elasticity_range[x])
)
elasticity_table

      PLANT COST_ELEMENT  ELASTICITY
0   PLANT 1           RM    0.932576
1   PLANT 1           PM    0.891600
2   PLANT 1           DL    0.721245
3   PLANT 1       OH_VAR    0.900185
4   PLANT 1       OH_FIX    0.000000
5   PLANT 2           RM    0.876508
6   PLANT 2           PM    0.933401
7   PLANT 2           DL    0.608891
8   PLANT 2       OH_VAR    0.964370
9   PLANT 2       OH_FIX    0.000000
10  PLANT 3           RM    0.927072
11  PLANT 3           PM    0.879254
12  PLANT 3           DL    0.623582
13  PLANT 3       OH_VAR    1.017765
14  PLANT 3       OH_FIX    0.000000
15  PLANT 4           RM    0.909807
16  PLANT 4           PM    0.868580
17  PLANT 4           DL    0.688662
18  PLANT 4       OH_VAR    0.927816
19  PLANT 4       OH_FIX    0.000000
20  PLANT 5           RM    0.856968
21  PLANT 5           PM    0.850316
22  PLANT 5           DL    0.608298
23  PLANT 5       OH_VAR    1.010506
24  PLANT 5       OH_FIX    0.000000
25  PLANT 6           RM    0.926873
26  PLANT 6           PM    0.907634
27  PLANT 6           DL    0.661586
28  PLANT 6       OH_VAR    1.031191
29  PLANT 6       OH_FIX    0.000000

### Finished Goods

In [8]:
n_goods = 5
goods = [f"FG{i+1:02d}" for i in range(n_goods)]
goods

['FG01', 'FG02', 'FG03', 'FG04', 'FG05']

---

# Fact Table Frame Skeleton

In [9]:
df = cc_df.assign(key=1).merge(
    pd.DataFrame({"PERIOD": periods, "key": 1}),
    on="key"
).drop("key", axis=1)
df.head(5)

     PLANT COST_CENTER      CAT_CC   PERIOD
0  PLANT 1    CC001P01  Production  2024-01
1  PLANT 1    CC001P01  Production  2024-02
2  PLANT 1    CC001P01  Production  2024-03
3  PLANT 1    CC001P01  Production  2024-04
4  PLANT 1    CC001P01  Production  2024-05

In [10]:
# cc_weight = np.random.randint(4,7,size=(len(cost_elements), len(cc_df)))
cc_weight = np.random.uniform(4, 7, size=(len(df), len(cost_elements)))
df[cost_elements['COST_ELEMENT']] = cc_weight

df[cost_elements['COST_ELEMENT']] = df[cost_elements['COST_ELEMENT']] / df.groupby(['PERIOD', 'PLANT', 'CAT_CC'])[cost_elements['COST_ELEMENT']].transform('sum')
df['QTY'] = (df['RM'] + df['PM']) / 2

df.head(10)

,PLANT,COST_CENTER,CAT_CC,PERIOD,RM,PM,DL,OH_FIX,OH_VAR,QTY
0,PLANT 1,CC001P01,Production,2024-01,0.292179,0.389361,0.296544,0.268536,0.380160,0.340770
1,PLANT 1,CC001P01,Production,2024-02,0.316834,0.317132,0.351508,0.315923,0.356928,0.316983
2,PLANT 1,CC001P01,Production,2024-03,0.316233,0.365736,0.289624,0.286031,0.362550,0.340984
3,PLANT 1,CC001P01,Production,2024-04,0.301176,0.346388,0.336764,0.326478,0.336176,0.323782
4,PLANT 1,CC001P01,Production,2024-05,0.256346,0.333194,0.292261,0.320501,0.414162,0.294770
5,PLANT 1,CC001P01,Production,2024-06,0.379955,0.296804,0.353627,0.342345,0.326490,0.338380
6,PLANT 1,CC001P01,Production,2024-07,0.301213,0.349978,0.303208,0.318280,0.264040,0.325595
7,PLANT 1,CC001P01,Production,2024-08,0.324546,0.375589,0.282978,0.309849,0.310743,0.350068
8,PLANT 1,CC001P01,Production,2024-09,0.265990,0.288597,0.295224,0.300253,0.322719,0.277294
9,PLANT 1,CC001P01,Production,2024-10,0.376596,0.371945,0.292846,0.333149,0.338964,0.374271

In [11]:
# CHECKING
df.groupby(['PERIOD', 'PLANT', 'CAT_CC']).agg({ce: 'sum' for ce in cost_elements['COST_ELEMENT']}).map(lambda x: round(x, 1) == 1.0).loc[lambda x: ~x['OH_FIX']]

Empty DataFrame
Columns: [RM, PM, DL, OH_FIX, OH_VAR]
Index: []

---

# Qty & Cost Modelling

### **1. BP**

In [12]:
pp = df[["PERIOD", "PLANT"]].drop_duplicates()

pp["ACTIVITY_INDEX"] = np.clip(
    np.random.normal(1.0, 0.1, len(pp)),
    0.8, 1.2
)

pp = pp.merge(plant_df, on="PLANT")
pp.head(5)

,PERIOD,PLANT,ACTIVITY_INDEX,SCALE,AUTOMATION_INDEX,DM_BIAS,DL_BIAS,CC_COUNT,PROD_CC_RATIO,PROD_VOLATILITY,RM_RATIO,PM_RATIO,OH_FIXED_RATIO,OH_VAR_RATIO
0,2024-01,PLANT 1,1.079289,0.622,-0.584,-0.018,0.018,4,0.85,0.077,0.729,0.271,0.262,0.738
1,2024-02,PLANT 1,0.891325,0.622,-0.584,-0.018,0.018,4,0.85,0.077,0.729,0.271,0.262,0.738
2,2024-03,PLANT 1,1.085186,0.622,-0.584,-0.018,0.018,4,0.85,0.077,0.729,0.271,0.262,0.738
3,2024-04,PLANT 1,1.100785,0.622,-0.584,-0.018,0.018,4,0.85,0.077,0.729,0.271,0.262,0.738
4,2024-05,PLANT 1,0.909974,0.622,-0.584,-0.018,0.018,4,0.85,0.077,0.729,0.271,0.262,0.738

#### Plant Level

In [13]:
base_qty = 10_000
cv = 0.12  # Coefficient of variation (adjust based on your volatility assumptions)
bound_pct = 0.30  # ±30% bounds

mean_qty = base_qty * pp["SCALE"] * pp["ACTIVITY_INDEX"]
pp["QTY"] = np.clip(
    np.random.normal(mean_qty, mean_qty * pp["PROD_VOLATILITY"]),
    mean_qty * (1 - bound_pct),
    mean_qty * (1 + bound_pct)
).astype(int)
# df = df.merge(pp, on=["PERIOD", "PLANT"])
# df
pp

,PERIOD,PLANT,ACTIVITY_INDEX,SCALE,AUTOMATION_INDEX,DM_BIAS,DL_BIAS,CC_COUNT,PROD_CC_RATIO,PROD_VOLATILITY,RM_RATIO,PM_RATIO,OH_FIXED_RATIO,OH_VAR_RATIO,QTY
0,2024-01,PLANT 1,1.079289,0.622,-0.584,-0.018,0.018,4,0.85,0.077,0.729,0.271,0.262,0.738,6665
1,2024-02,PLANT 1,0.891325,0.622,-0.584,-0.018,0.018,4,0.85,0.077,0.729,0.271,0.262,0.738,6140
2,2024-03,PLANT 1,1.085186,0.622,-0.584,-0.018,0.018,4,0.85,0.077,0.729,0.271,0.262,0.738,6793
3,2024-04,PLANT 1,1.100785,0.622,-0.584,-0.018,0.018,4,0.85,0.077,0.729,0.271,0.262,0.738,6608
4,2024-05,PLANT 1,0.909974,0.622,-0.584,-0.018,0.018,4,0.85,0.077,0.729,0.271,0.262,0.738,5115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,2025-08,PLANT 6,0.964960,1.029,-0.894,-0.027,0.027,8,0.85,0.125,0.726,0.274,0.216,0.784,11014
140,2025-09,PLANT 6,1.088843,1.029,-0.894,-0.027,0.027,8,0.85,0.125,0.726,0.274,0.216,0.784,11050
141,2025-10,PLANT 6,1.200000,1.029,-0.894,-0.027,0.027,8,0.85,0.125,0.726,0.274,0.216,0.784,12719
142,2025-11,PLANT 6,0.906906,1.029,-0.894,-0.027,0.027,8,0.85,0.125,0.726,0.274,0.216,0.784,9889
143,2025-12,PLANT 6,1.108710,1.029,-0.894,-0.027,0.027,8,0.85,0.125,0.726,0.274,0.216,0.784,12981

In [14]:
base_cost = 80_000_000

# Base fixed ratio from automation, plus random variation per period
base_fixed_ratio = 0.5 + 0.15 * pp["AUTOMATION_INDEX"]
random_variation = np.random.uniform(-0.10, 0.10, len(pp))  # ±10% noise
pp["FIXED"] = base_fixed_ratio + random_variation
pp['VARIABLE'] = 1 - pp["FIXED"]

pp["DM_RATIO"] = np.random.uniform(0.55, 0.65, len(pp)) + pp["DM_BIAS"]
pp["DL_RATIO"] = np.random.uniform(0.20, 0.30, len(pp)) + pp["DL_BIAS"]
pp["OH_RATIO"] = 1 - pp["DM_RATIO"] - pp["DL_RATIO"]

# Cost with both realistic (automation-driven) and stochastic components
pp["COST"] = base_cost * pp["SCALE"] * (pp["VARIABLE"] * pp["ACTIVITY_INDEX"] + pp["FIXED"])
pp['RM'] = pp["COST"] * pp["DM_RATIO"] * pp["RM_RATIO"]
pp['PM'] = pp["COST"] * pp["DM_RATIO"] * pp["PM_RATIO"]
pp['DL'] = pp["COST"] * pp["DL_RATIO"]
pp['OH_FIX'] = pp["COST"] * pp["OH_RATIO"] * pp["OH_FIXED_RATIO"]
pp['OH_VAR'] = pp["COST"] * pp["OH_RATIO"] * pp["OH_VAR_RATIO"]

pp.head(5).style.format({"COST": "{:,.2f}", "RM": "{:,.2f}", "PM": "{:,.2f}", "DL": "{:,.2f}", "OH_FIX": "{:,.2f}", "OH_VAR": "{:,.2f}"})

In [15]:
BP_plant = pp[[
    "PERIOD", "PLANT", "QTY", "COST", "RM", "PM", "DL", "OH_FIX", "OH_VAR"
]].groupby(["PERIOD", "PLANT"]).agg({
    "QTY": "sum",
    "COST": "sum",
    "RM": "sum",
    "PM": "sum",
    "DL": "sum",
    "OH_FIX": "sum",
    "OH_VAR": "sum",
})

BP_plant.head(5).style.format({"COST": "{:,.2f}", "RM": "{:,.2f}", "PM": "{:,.2f}", "DL": "{:,.2f}", "OH_FIX": "{:,.2f}", "OH_VAR": "{:,.2f}"})

#### CC Breakdown

In [16]:
alloc_map = pd.DataFrame({
    "RM": {"Production": 1.0, "Supporting": 0.0},
    "PM": {"Production": 1.0, "Supporting": 0.0},
    "DL": {"Production": 0.7, "Supporting": 0.3},
    "OH_FIX": {"Production": 0.6, "Supporting": 0.4},
    "OH_VAR": {"Production": 0.5, "Supporting": 0.5},
})

alloc_map

             RM   PM   DL  OH_FIX  OH_VAR
Production  1.0  1.0  0.7     0.6     0.5
Supporting  0.0  0.0  0.3     0.4     0.5

In [17]:
# Merge once
BP = df.merge(
    BP_plant,
    on=['PERIOD', 'PLANT'],
    how='left',
    suffixes=('', '_PLANT')
)

# QTY
mask_prod = BP['CAT_CC'] == 'Production'
BP.loc[~mask_prod, 'QTY'] = 0
BP.loc[mask_prod, 'QTY'] = BP.loc[mask_prod, 'QTY_PLANT'] * BP.loc[mask_prod, 'QTY']

# Cost allocation (fully vectorized, no apply, no melt)
for ce in cost_elements['COST_ELEMENT']:
    BP[ce] = (
        BP[ce] *
        BP[f"{ce}_PLANT"] *
        BP['CAT_CC'].map(alloc_map[ce])
    )

# --- DROP helper columns (important part) ---
cols_to_drop = [col for col in BP.columns if col.endswith('_PLANT')]
BP.drop(columns=cols_to_drop, inplace=True)

BP.head(5).style.format({"COST": "{:,.2f}", "RM": "{:,.2f}", "PM": "{:,.2f}", "DL": "{:,.2f}", "OH_FIX": "{:,.2f}", "OH_VAR": "{:,.2f}"})

#### FG Breakdown

In [18]:
BP_QTY = BP.loc[BP['CAT_CC'] == 'Production', ['PERIOD', 'PLANT', 'COST_CENTER', 'QTY']].copy()

n = len(BP_QTY)
m = len(goods)
mask = np.random.randint(0, 8, size=(n, m)) != 0
rand_float = np.random.uniform(2, 6, size=(n, m))

BP_QTY[goods] = np.where(mask, rand_float, 0)
BP_QTY = pd.melt(BP_QTY, id_vars=['PERIOD', 'PLANT', 'COST_CENTER', 'QTY'], value_vars=goods, var_name='FG', value_name='QTY_ALLOC')
BP_QTY['QTY'] = BP_QTY['QTY_ALLOC'] / BP_QTY.groupby(['PERIOD', 'PLANT', 'COST_CENTER'])['QTY_ALLOC'].transform('sum') * BP_QTY['QTY']
BP_QTY.drop(columns=['QTY_ALLOC'], inplace=True)

BP_QTY.head(5)

    PERIOD    PLANT COST_CENTER         QTY    FG
0  2024-01  PLANT 1    CC001P01  402.652611  FG01
1  2024-02  PLANT 1    CC001P01  436.939367  FG01
2  2024-03  PLANT 1    CC001P01  563.416699  FG01
3  2024-04  PLANT 1    CC001P01  369.323121  FG01
4  2024-05  PLANT 1    CC001P01  327.748144  FG01

In [19]:
BP_QTY.groupby(['PERIOD', 'PLANT', 'COST_CENTER']).agg({'QTY': 'sum'})

                                     QTY
PERIOD  PLANT   COST_CENTER
2024-01 PLANT 1 CC001P01     2271.234085
                CC001P02     2114.780520
                CC001P03     2278.985395
        PLANT 2 CC002P01     2453.322705
                CC002P02     2706.012697
...                                  ...
2025-12 PLANT 6 CC006P02     2613.687314
                CC006P03     2002.551373
                CC006P04     2060.331990
                CC006P05     1969.840001
                CC006P06     2382.139774

[840 rows x 1 columns]

In [20]:
pd.melt(
    BP.groupby(['PERIOD', 'PLANT']).agg({ce: 'sum' for ce in cost_elements['COST_ELEMENT']}).reset_index(),
    id_vars=['PERIOD', 'PLANT'],
    value_vars=cost_elements['COST_ELEMENT'].tolist(),
    var_name='COST_ELEMENT',
    value_name='COST'
).groupby(['PERIOD', 'PLANT']).agg({'COST': 'sum'}).head(5).style.format({"COST": "{:,.2f}"})

In [21]:
BP.drop(columns=['COST'], inplace=True)
BP = pd.melt(
    BP, 
    id_vars=['PERIOD', 'PLANT', 'COST_CENTER', 'CAT_CC'], 
    value_vars=cost_elements['COST_ELEMENT'].tolist(), 
    var_name='COST_ELEMENT', 
    value_name='COST'
)

BP.head(10).style.format({"COST": "{:,.2f}"})

### **2. Actual**

In [22]:
pa = df[["PERIOD", "PLANT"]].drop_duplicates()

pa["ACTIVITY_INDEX"] = np.clip(
    np.random.normal(1.0, 0.1, len(pa)),
    0.8, 1.2
)

pa = pa.merge(plant_df, on="PLANT")
pa

,PERIOD,PLANT,ACTIVITY_INDEX,SCALE,AUTOMATION_INDEX,DM_BIAS,DL_BIAS,CC_COUNT,PROD_CC_RATIO,PROD_VOLATILITY,RM_RATIO,PM_RATIO,OH_FIXED_RATIO,OH_VAR_RATIO
0,2024-01,PLANT 1,0.933612,0.622,-0.584,-0.018,0.018,4,0.85,0.077,0.729,0.271,0.262,0.738
1,2024-02,PLANT 1,0.800000,0.622,-0.584,-0.018,0.018,4,0.85,0.077,0.729,0.271,0.262,0.738
2,2024-03,PLANT 1,1.057046,0.622,-0.584,-0.018,0.018,4,0.85,0.077,0.729,0.271,0.262,0.738
3,2024-04,PLANT 1,1.009865,0.622,-0.584,-0.018,0.018,4,0.85,0.077,0.729,0.271,0.262,0.738
4,2024-05,PLANT 1,1.012408,0.622,-0.584,-0.018,0.018,4,0.85,0.077,0.729,0.271,0.262,0.738
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,2025-08,PLANT 6,0.925853,1.029,-0.894,-0.027,0.027,8,0.85,0.125,0.726,0.274,0.216,0.784
140,2025-09,PLANT 6,0.990177,1.029,-0.894,-0.027,0.027,8,0.85,0.125,0.726,0.274,0.216,0.784
141,2025-10,PLANT 6,1.087926,1.029,-0.894,-0.027,0.027,8,0.85,0.125,0.726,0.274,0.216,0.784
142,2025-11,PLANT 6,0.854378,1.029,-0.894,-0.027,0.027,8,0.85,0.125,0.726,0.274,0.216,0.784
143,2025-12,PLANT 6,0.956533,1.029,-0.894,-0.027,0.027,8,0.85,0.125,0.726,0.274,0.216,0.784

#### Plant Level

In [23]:
# base_qty = 10_000
# cv = 0.12  # Coefficient of variation (adjust based on your volatility assumptions)
# bound_pct = 0.30  # ±30% bounds

mean_qty = base_qty * pa["SCALE"] * pa["ACTIVITY_INDEX"]
pa["QTY"] = np.clip(
    np.random.normal(mean_qty, mean_qty * pa["PROD_VOLATILITY"]),
    mean_qty * (1 - bound_pct),
    mean_qty * (1 + bound_pct)
).astype(int)
# df = df.merge(pa, on=["PERIOD", "PLANT"])
# df
pa

,PERIOD,PLANT,ACTIVITY_INDEX,SCALE,AUTOMATION_INDEX,DM_BIAS,DL_BIAS,CC_COUNT,PROD_CC_RATIO,PROD_VOLATILITY,RM_RATIO,PM_RATIO,OH_FIXED_RATIO,OH_VAR_RATIO,QTY
0,2024-01,PLANT 1,0.933612,0.622,-0.584,-0.018,0.018,4,0.85,0.077,0.729,0.271,0.262,0.738,5191
1,2024-02,PLANT 1,0.800000,0.622,-0.584,-0.018,0.018,4,0.85,0.077,0.729,0.271,0.262,0.738,5119
2,2024-03,PLANT 1,1.057046,0.622,-0.584,-0.018,0.018,4,0.85,0.077,0.729,0.271,0.262,0.738,7224
3,2024-04,PLANT 1,1.009865,0.622,-0.584,-0.018,0.018,4,0.85,0.077,0.729,0.271,0.262,0.738,5794
4,2024-05,PLANT 1,1.012408,0.622,-0.584,-0.018,0.018,4,0.85,0.077,0.729,0.271,0.262,0.738,6563
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,2025-08,PLANT 6,0.925853,1.029,-0.894,-0.027,0.027,8,0.85,0.125,0.726,0.274,0.216,0.784,8879
140,2025-09,PLANT 6,0.990177,1.029,-0.894,-0.027,0.027,8,0.85,0.125,0.726,0.274,0.216,0.784,9632
141,2025-10,PLANT 6,1.087926,1.029,-0.894,-0.027,0.027,8,0.85,0.125,0.726,0.274,0.216,0.784,12061
142,2025-11,PLANT 6,0.854378,1.029,-0.894,-0.027,0.027,8,0.85,0.125,0.726,0.274,0.216,0.784,6946
143,2025-12,PLANT 6,0.956533,1.029,-0.894,-0.027,0.027,8,0.85,0.125,0.726,0.274,0.216,0.784,10287

In [24]:
# base_cost = 80_000_000

# Base fixed ratio from automation, plus random variation per period
base_fixed_ratio = 0.5 + 0.15 * pa["AUTOMATION_INDEX"]
random_variation = np.random.uniform(-0.10, 0.10, len(pa))  # ±10% noise
pa["FIXED"] = base_fixed_ratio + random_variation
pa['VARIABLE'] = 1 - pa["FIXED"]

pa["DM_RATIO"] = np.random.uniform(0.55, 0.65, len(pa)) + pa["DM_BIAS"]
pa["DL_RATIO"] = np.random.uniform(0.20, 0.30, len(pa)) + pa["DL_BIAS"]
pa["OH_RATIO"] = 1 - pa["DM_RATIO"] - pa["DL_RATIO"]

# Cost with both realistic (automation-driven) and stochastic components
pa["COST"] = base_cost * pa["SCALE"] * (pa["VARIABLE"] * pa["ACTIVITY_INDEX"] + pa["FIXED"])
pa['RM'] = pa["COST"] * pa["DM_RATIO"] * pa["RM_RATIO"]
pa['PM'] = pa["COST"] * pa["DM_RATIO"] * pa["PM_RATIO"]
pa['DL'] = pa["COST"] * pa["DL_RATIO"]
pa['OH_FIX'] = pa["COST"] * pa["OH_RATIO"] * pa["OH_FIXED_RATIO"]
pa['OH_VAR'] = pa["COST"] * pa["OH_RATIO"] * pa["OH_VAR_RATIO"]

pa.head(5).style.format({"COST": "{:,.2f}", "RM": "{:,.2f}", "PM": "{:,.2f}", "DL": "{:,.2f}", "OH_FIX": "{:,.2f}", "OH_VAR": "{:,.2f}"})

In [25]:
act_plant = pa[[
    "PERIOD", "PLANT", "QTY", "COST", "RM", "PM", "DL", "OH_FIX", "OH_VAR"
]].groupby(["PERIOD", "PLANT"]).agg({
    "QTY": "sum",
    "COST": "sum",
    "RM": "sum",
    "PM": "sum",
    "DL": "sum",
    "OH_FIX": "sum",
    "OH_VAR": "sum",
})

act_plant.head(5).style.format({"COST": "{:,.2f}", "RM": "{:,.2f}", "PM": "{:,.2f}", "DL": "{:,.2f}", "OH_FIX": "{:,.2f}", "OH_VAR": "{:,.2f}"})

#### CC Breakdown

In [26]:
# alloc_map = pd.DataFrame({
#     "RM": {"Production": 1.0, "Supporting": 0.0},
#     "PM": {"Production": 1.0, "Supporting": 0.0},
#     "DL": {"Production": 0.7, "Supporting": 0.3},
#     "OH_FIX": {"Production": 0.6, "Supporting": 0.4},
#     "OH_VAR": {"Production": 0.5, "Supporting": 0.5},
# })

# alloc_map

In [27]:
# Merge once
act = df.merge(
    act_plant,
    on=['PERIOD', 'PLANT'],
    how='left',
    suffixes=('', '_PLANT')
)

# QTY
mask_prod = act['CAT_CC'] == 'Production'
act.loc[~mask_prod, 'QTY'] = 0
act.loc[mask_prod, 'QTY'] = act.loc[mask_prod, 'QTY_PLANT'] * act.loc[mask_prod, 'QTY']

# Cost allocation (fully vectorized, no apply, no melt)
for ce in cost_elements['COST_ELEMENT']:
    act[ce] = (
        act[ce] *
        act[f"{ce}_PLANT"] *
        act['CAT_CC'].map(alloc_map[ce])
    )

# --- DROP helper columns (important part) ---
cols_to_drop = [col for col in act.columns if col.endswith('_PLANT')]
act.drop(columns=cols_to_drop, inplace=True)

act.head(5).style.format({"COST": "{:,.2f}", "RM": "{:,.2f}", "PM": "{:,.2f}", "DL": "{:,.2f}", "OH_FIX": "{:,.2f}", "OH_VAR": "{:,.2f}"})

#### FG Breakdown

In [28]:
act_QTY = act.loc[act['CAT_CC'] == 'Production', ['PERIOD', 'PLANT', 'COST_CENTER', 'QTY']].copy()

n = len(act_QTY)
m = len(goods)
# mask = np.random.randint(0, 8, size=(n, m)) != 0
# rand_float = np.random.uniform(2, 6, size=(n, m))

act_QTY[goods] = np.where(mask, rand_float, 0)
act_QTY = pd.melt(act_QTY, id_vars=['PERIOD', 'PLANT', 'COST_CENTER', 'QTY'], value_vars=goods, var_name='FG', value_name='QTY_ALLOC')
act_QTY['QTY'] = act_QTY['QTY_ALLOC'] / act_QTY.groupby(['PERIOD', 'PLANT', 'COST_CENTER'])['QTY_ALLOC'].transform('sum') * act_QTY['QTY']
act_QTY.drop(columns=['QTY_ALLOC'], inplace=True)

act_QTY.head(5)

    PERIOD    PLANT COST_CENTER         QTY    FG
0  2024-01  PLANT 1    CC001P01  313.603856  FG01
1  2024-02  PLANT 1    CC001P01  364.282185  FG01
2  2024-03  PLANT 1    CC001P01  599.164174  FG01
3  2024-04  PLANT 1    CC001P01  323.828415  FG01
4  2024-05  PLANT 1    CC001P01  420.530023  FG01

In [29]:
act.drop(columns=['COST'], inplace=True)
act = pd.melt(
    act, 
    id_vars=['PERIOD', 'PLANT', 'COST_CENTER', 'CAT_CC'], 
    value_vars=cost_elements['COST_ELEMENT'].tolist(), 
    var_name='COST_ELEMENT', 
    value_name='COST'
)

act.head(10).style.format({"COST": "{:,.2f}"})

---

# Output

### Cost

In [30]:
BP.merge(
    cost_elements,
    how='left',
    left_on='COST_ELEMENT',
    right_on='COST_ELEMENT'
)[['PERIOD', 'PLANT', 'COST_CENTER', 'CAT_CC', 'CAT_GL', 'COST_ELEMENT', 'COST']].merge(
    act,
    how='outer',
    left_on=['PERIOD', 'PLANT', 'COST_CENTER', 'CAT_CC', 'COST_ELEMENT'],
    right_on=['PERIOD', 'PLANT', 'COST_CENTER', 'CAT_CC', 'COST_ELEMENT'],
    suffixes=('_BP', '_ACT')
).to_excel("FACT_COST.xlsx", index=False)

In [31]:
BP_QTY[['PERIOD', 'PLANT', 'COST_CENTER', 'FG', 'QTY']].merge(
    act_QTY,
    how='outer',
    left_on=['PERIOD', 'PLANT', 'COST_CENTER', 'FG'],
    right_on=['PERIOD', 'PLANT', 'COST_CENTER', 'FG'],
    suffixes=('_BP', '_ACT')
).to_excel("FACT_QTY.xlsx", index=False)

In [32]:
BP.merge(
    cost_elements,
    how='left',
    left_on='COST_ELEMENT',
    right_on='COST_ELEMENT'
)

,PERIOD,PLANT,COST_CENTER,CAT_CC,COST_ELEMENT,COST,CAT_GL
0,2024-01,PLANT 1,CC001P01,Production,RM,6.907105e+06,DM
1,2024-02,PLANT 1,CC001P01,Production,RM,6.752731e+06,DM
2,2024-03,PLANT 1,CC001P01,Production,RM,6.882021e+06,DM
3,2024-04,PLANT 1,CC001P01,Production,RM,6.748523e+06,DM
4,2024-05,PLANT 1,CC001P01,Production,RM,5.171938e+06,DM
...,...,...,...,...,...,...,...
5635,2025-08,PLANT 6,CC006S02,Supporting,OH_VAR,1.637127e+06,OH
5636,2025-09,PLANT 6,CC006S02,Supporting,OH_VAR,3.997199e+06,OH
5637,2025-10,PLANT 6,CC006S02,Supporting,OH_VAR,4.381948e+06,OH
5638,2025-11,PLANT 6,CC006S02,Supporting,OH_VAR,2.332213e+06,OH
5639,2025-12,PLANT 6,CC006S02,Supporting,OH_VAR,2.485230e+06,OH